### ISSUE TITLE
Parse Django model meta options to create accurate initial_data.json

### ISSUE THREAD

**Issue by njamaleddine** [njamaleddine/django-csvtojson#3]
- [ ] Get proper field data types from django models
  - https://docs.djangoproject.com/en/1.8/ref/models/options/
- [ ] Fall back to using headers of a csv for field type 
- [ ] Add more robust validation
